Add wait-on-login to all docker scripts

diff --git a/wait-on-login b/wait-on-login
--- a/wait-on-login
+++ b/wait-on-login
@@ -8,17 +8,26 @@ OMERO_PASS=${OMERO_PASS:-omero}
 
 export PATH=$PATH:${OMERO_DIST}/bin
 
+
 max_attempts=10
 attempt_num=1
+
+function end {
+    printf "travis_fold:end:wait-on-login\n"
+}
+
+trap end EXIT
+
+printf "travis_fold:start:wait-on-login\n"
 until omero login $OMERO_USER@$OMERO_HOST:$OMERO_PORT -w $OMERO_PASS 2>&1 >/dev/null
 do
     if (( attempt_num == max_attempts ))
     then
         echo "All attempts failed"
         exit 1
-    else
-        echo "Attempt $(( attempt_num++ )) failed. Trying again in $attempt_num seconds..."
-        sleep $attempt_num
     fi
+
+    echo "Attempt $(( attempt_num++ )) failed. Trying again in $attempt_num seconds..."
+    sleep $attempt_num
+
 done
-exit 0
